services:
  php:
    build: 
      context: .
      dockerfile: docker/Dockerfile      
    container_name: santander_pay_slip_test_php
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    working_dir: /var/www
    ports:
      - 8090:8090
    command: php -S 0.0.0.0:8090 -t /var/www